### ISSUE TITLE
update MADS fields when they are empty

### ISSUE THREAD

**Issue by dongourley** [WRLC/orcid_task_service#16] opened 2018-01-04 16:52 UTC
I had said to only update the u1 identifier when I PUT a request for an existing MADS, but talking to @krebeck we wondered if you could update other fields from the JSON request if the corresponding MADS element was missing or empty?

**Comment by ihardy** [comment] 2018-01-04 17:02
Sure, we should be able to put anything in from the request in to the new updated MADS.

I should mention, the update isn't a true update, it's a delete and create.

DGI has confirmed that this is a limitation of the Islandora API: "It looks like the update datastream content was never properly implemented into the Rest API...") They are going to look into how an implementation fits into the road map

We'll just need to have a rule for which fields should be updated if present. 

references https://github.com/WRLC/orcid_task_service/issues/17

**Comment by dongourley** [comment] 2018-01-04 18:34
> We'll just need to have a rule for which fields should be updated if present.

I assume you mean present _in the request_ (no fields should be updated if present _in the MADS_ except possibly the u1 identifier, depending on how #15 is implemented). I think you should add any field present in the request to the MADS if it is not in the MADS or is an empty \<tag /> in the MADS. 

@krebeck , what do you think?

**Comment by ihardy** [comment] 2018-02-12 21:07
Yay or Nay on this one?

Right now, we're only updating u1. Did we want to add anything else. If not I'll close this.

**Comment by krebeck** [comment] 2018-02-12 21:09
It's not going to be an issue for anyone but the few folks with existing MADS.  I think it's out of scope for now.

**Comment by ihardy** [comment] 2018-02-12 21:11
Ok, I'll close this, we can re-open if we end up expanding the scope.

**Closed as completed by ihardy** 2018-02-12 21:11 UTC
Labels: out of scope
